//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel;

	public partial class appointments
    {
        public int idAppointment { get; set; }
		[DisplayName("Date et Heure")]
		public System.DateTime dateHour { get; set; }
		[DisplayName("Nom du courtier")]
		public int idBroker { get; set; }
		[DisplayName("Nom du client")]
		public int idCustomer { get; set; }

		public virtual brokers brokers { get; set; }
		public virtual customers customers { get; set; }
    }
}
