//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel;

	public partial class customers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customers()
        {
            this.appointments = new HashSet<appointments>();
        }
        public int idCustomer { get; set; }
		[DisplayName("Nom du client")]
		public string lastname { get; set; }
		[DisplayName("Prenom du client")]
		public string firstname { get; set; }
		[DisplayName("Mail")]
		public string mail { get; set; }
		[DisplayName("Télephone")]
		public string phoneNumber { get; set; }
		[DisplayName("Budget")]
		public int budget { get; set; }
		[DisplayName("Sujet")]
		public string subject { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<appointments> appointments { get; set; }
    }
}
